#
# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u8185/extract-files
#    vendor/huawei/u8185/props/system/lib/libC2D2.so:system/lib/libC2D2.so \
#    vendor/huawei/u8185/props/system/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
#    vendor/huawei/u8185/props/system/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \

PRODUCT_COPY_FILES += \
    vendor/huawei/u8185/props/system/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/huawei/u8185/props/system/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/huawei/u8185/props/system/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/huawei/u8185/props/system/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/huawei/u8185/props/system/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/huawei/u8185/props/system/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/huawei/u8185/props/system/lib/libgsl.so:system/lib/libgsl.so \
    vendor/huawei/u8185/props/system/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/huawei/u8185/props/system/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/huawei/u8185/props/system/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/huawei/u8185/props/system/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/huawei/u8185/props/system/lib/hw/copybit.msm7k.so:system/lib/hw/copybit.msm7k.so \
    vendor/huawei/u8185/props/system/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/huawei/u8185/props/system/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/huawei/u8185/props/system/lib/hw/gralloc.msm7k.so:system/lib/hw/gralloc.msm7k.so \
    vendor/huawei/u8185/props/system/lib/hw/libloc_eng_v01.default.so:system/lib/hw/libloc_eng_v01.default.so \
    vendor/huawei/u8185/props/system/lib/hw/libqcomfm_if.so:system/lib/hw/libqcomfm_if.so \
    vendor/huawei/u8185/props/system/lib/hw/lights.msm7k.so:system/lib/hw/lights.msm7k.so \
    vendor/huawei/u8185/props/system/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so
